// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwjkbitqnbgovhxxkpgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3amtiaXRxbmJnb3ZoeHhrcGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODg3NTgsImV4cCI6MjA3MzA2NDc1OH0.fydzlq7R6k03j0aLikYv1OMZiFo0l9hrImgW2HoAXuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});